spring:
  application:
    name: wallet
  datasource:
    url: jdbc:h2:mem:walletdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
rpTest:
  jwt:
    secret: igordamiano-wallet-service-assignment
    #secret: pepe-ja-tirei-a-vela
    expiration: 60480000 # in seconds

# Swagger docs at /swagger-ui.html or /swagger-ui/index.html

